services:
  #Auth Db
  auth-db:
    image: "postgres:latest"
    container_name: auth-db
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=123w
  #tokens Db
  cache:
    image: "redis:latest"
    container_name: 'cache'
    restart: always
    ports:
      - 1919:6379
