services:
  #Auth Db
  auth-db:
    image: "postgres:latest"
    container_name: auth-db
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=123w
    volumes:
      - pg_data:/var/lib/postgresql/data
  #tokens Db
  auth-cache:
    image: "redis:latest"
    container_name: auth-cache
    restart: always
    ports:
      - 1919:6379

volumes:
  pg_data:
