services:
  #Auth Db
  auth-db-test:
    image: "postgres:latest"
    container_name: auth-db-test
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=123w
    volumes:
      - pg_data:/var/lib/postgresql/data
  #tokens Db
  auth-cache-test:
    image: "redis:latest"
    container_name: auth-cache-test
    restart: always
    ports:
      - 1919:6379

volumes:
  pg_data:
