// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RatingService.Infrastructure.DataAccess;

#nullable disable

namespace RatingService.Infrastructure.Migrations
{
    [DbContext(typeof(RatingServiceDbContext))]
    partial class RatingServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("RatingService.Domain.Aggregates.EventInfo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("RatingService.Domain.Aggregates.UserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RatingService.Domain.Entities.EventRatingUpdate", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("EventRatingUpdate");
                });

            modelBuilder.Entity("RatingService.Domain.Entities.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserInfoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserInfoId");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("RatingService.Domain.Entities.Participant", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParticipationState")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Participant");
                });

            modelBuilder.Entity("RatingService.Domain.Entities.Rating", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Rating");
                });

            modelBuilder.Entity("RatingService.Domain.Entities.UserRatingUpdate", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RatingUpdates");
                });

            modelBuilder.Entity("RatingService.Domain.Aggregates.EventInfo", b =>
                {
                    b.HasOne("RatingService.Domain.Entities.Rating", "Rating")
                        .WithOne()
                        .HasForeignKey("RatingService.Domain.Aggregates.EventInfo", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("RatingService.Domain.Entities.EventRatingUpdate", b =>
                {
                    b.HasOne("RatingService.Domain.Entities.Rating", "Rating")
                        .WithOne()
                        .HasForeignKey("RatingService.Domain.Entities.EventRatingUpdate", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("RatingService.Domain.Entities.Feedback", b =>
                {
                    b.HasOne("RatingService.Domain.Aggregates.EventInfo", null)
                        .WithMany("Feedbacks")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RatingService.Domain.Aggregates.UserInfo", null)
                        .WithMany("OrganizerFeedbacks")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RatingService.Domain.Aggregates.UserInfo", null)
                        .WithMany("GamerFeedbacks")
                        .HasForeignKey("UserInfoId");

                    b.OwnsOne("RatingService.Domain.ValueObjects.FeedbackContent", "Content", b1 =>
                        {
                            b1.Property<int>("FeedbackId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("FeedbackId");

                            b1.ToTable("Feedback");

                            b1.WithOwner()
                                .HasForeignKey("FeedbackId");
                        });

                    b.OwnsOne("RatingService.Domain.ValueObjects.Receiver", "Receiver", b1 =>
                        {
                            b1.Property<int>("FeedbackId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("FeedbackId");

                            b1.ToTable("Feedback");

                            b1.WithOwner()
                                .HasForeignKey("FeedbackId");
                        });

                    b.Navigation("Content")
                        .IsRequired();

                    b.Navigation("Receiver")
                        .IsRequired();
                });

            modelBuilder.Entity("RatingService.Domain.Entities.Participant", b =>
                {
                    b.HasOne("RatingService.Domain.Aggregates.EventInfo", null)
                        .WithMany("Participants")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RatingService.Domain.Entities.Rating", "Rating")
                        .WithOne()
                        .HasForeignKey("RatingService.Domain.Entities.Participant", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("RatingService.Domain.Entities.Rating", b =>
                {
                    b.HasOne("RatingService.Domain.Aggregates.UserInfo", null)
                        .WithMany("RatingsByCategory")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RatingService.Domain.Entities.UserRatingUpdate", b =>
                {
                    b.HasOne("RatingService.Domain.Entities.Rating", "Rating")
                        .WithOne()
                        .HasForeignKey("RatingService.Domain.Entities.UserRatingUpdate", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("RatingService.Domain.Aggregates.EventInfo", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("RatingService.Domain.Aggregates.UserInfo", b =>
                {
                    b.Navigation("GamerFeedbacks");

                    b.Navigation("OrganizerFeedbacks");

                    b.Navigation("RatingsByCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
