services:
  #Events Db
  events-db-test:
    image: "postgres:latest"
    container_name: events-db-test
    restart: always
    ports:
      - 5434:5432
    environment:
      - POSTGRES_PASSWORD=123w
  #tokens Db
  events-cache-test:
    image: "redis:latest"
    container_name: events-cache-test
    restart: always
    ports:
      - 1920:6379
  # s3 storage
  events-s3-test:
    image: minio/minio:latest
    container_name: events-s3-test
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

volumes:
  minio-data:
