// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RatingService.Infrastructure.DataAccess;

#nullable disable

namespace RatingService.Infrastructure.Migrations
{
    [DbContext(typeof(RatingServiceDbContext))]
    [Migration("20241229185912_InitialMigration-3")]
    partial class InitialMigration3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ratings")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RatingService.Domain.Aggregates.EventInfo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("integer")
                        .HasColumnName("organizer_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("events_info", "ratings");
                });

            modelBuilder.Entity("RatingService.Domain.Aggregates.UserInfo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users_info", "ratings");
                });

            modelBuilder.Entity("RatingService.Domain.Entities.EventRatingUpdate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<int>("RatingId")
                        .HasColumnType("integer")
                        .HasColumnName("rating_id");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<float>("Value")
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("RatingId");

                    b.ToTable("events_ratings_updates", "ratings");
                });

            modelBuilder.Entity("RatingService.Domain.Entities.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<int?>("EventInfoId")
                        .HasColumnType("integer");

                    b.Property<int>("ExternalEventId")
                        .HasColumnType("integer")
                        .HasColumnName("external_event_id");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<int?>("UserInfoId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserInfoId1")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventInfoId");

                    b.HasIndex("ExternalEventId");

                    b.HasIndex("UserInfoId");

                    b.HasIndex("UserInfoId1");

                    b.ToTable("feedbacks", "ratings");
                });

            modelBuilder.Entity("RatingService.Domain.Entities.Participant", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("EventInfoId")
                        .HasColumnType("integer")
                        .HasColumnName("event_info_id");

                    b.Property<string>("ParticipationState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("participation_state");

                    b.Property<int>("UserInfoId")
                        .HasColumnType("integer")
                        .HasColumnName("user_info_id");

                    b.HasKey("Id");

                    b.HasIndex("EventInfoId");

                    b.HasIndex("UserInfoId");

                    b.ToTable("participants", "ratings");
                });

            modelBuilder.Entity("RatingService.Domain.Entities.ParticipantRatingUpdate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<int>("RatingId")
                        .HasColumnType("integer")
                        .HasColumnName("rating_id");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<float>("Value")
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("RatingId");

                    b.ToTable("participants_ratings_updates", "ratings");
                });

            modelBuilder.Entity("RatingService.Domain.Entities.Ratings.EventRating", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("EventInfoId")
                        .HasColumnType("integer")
                        .HasColumnName("event_info_id");

                    b.Property<int>("OrganizerRatingId")
                        .HasColumnType("integer")
                        .HasColumnName("organizer_rating_id");

                    b.Property<float>("Value")
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("EventInfoId")
                        .IsUnique();

                    b.HasIndex("OrganizerRatingId");

                    b.ToTable("events_ratings", "ratings");
                });

            modelBuilder.Entity("RatingService.Domain.Entities.Ratings.GamerRating", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("UserInfoId")
                        .HasColumnType("integer")
                        .HasColumnName("user_info_id");

                    b.Property<float>("Value")
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("UserInfoId")
                        .IsUnique();

                    b.ToTable("gamers_ratings", "ratings");
                });

            modelBuilder.Entity("RatingService.Domain.Entities.Ratings.OrganizerRating", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("UserInfoId")
                        .HasColumnType("integer")
                        .HasColumnName("user_info_id");

                    b.Property<float>("Value")
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("UserInfoId")
                        .IsUnique();

                    b.ToTable("organizers_ratings", "ratings");
                });

            modelBuilder.Entity("RatingService.Domain.Entities.Ratings.ParticipantRating", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("GamerRatingId")
                        .HasColumnType("integer")
                        .HasColumnName("gamer_rating_id");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer")
                        .HasColumnName("participant_id");

                    b.Property<float>("Value")
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("GamerRatingId");

                    b.HasIndex("ParticipantId")
                        .IsUnique();

                    b.ToTable("participants_ratings", "ratings");
                });

            modelBuilder.Entity("RatingService.Domain.Entities.EventRatingUpdate", b =>
                {
                    b.HasOne("RatingService.Domain.Entities.Ratings.EventRating", null)
                        .WithMany("Updates")
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RatingService.Domain.Entities.Feedback", b =>
                {
                    b.HasOne("RatingService.Domain.Aggregates.EventInfo", null)
                        .WithMany("Feedbacks")
                        .HasForeignKey("EventInfoId");

                    b.HasOne("RatingService.Domain.Aggregates.EventInfo", null)
                        .WithMany()
                        .HasForeignKey("ExternalEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RatingService.Domain.Aggregates.UserInfo", null)
                        .WithMany("GamerFeedbacks")
                        .HasForeignKey("UserInfoId");

                    b.HasOne("RatingService.Domain.Aggregates.UserInfo", null)
                        .WithMany("OrganizerFeedbacks")
                        .HasForeignKey("UserInfoId1");

                    b.OwnsOne("RatingService.Domain.ValueObjects.Receiver", "Receiver", b1 =>
                        {
                            b1.Property<int>("FeedbackId")
                                .HasColumnType("integer");

                            b1.Property<string>("EntityType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("entity_type");

                            b1.Property<int>("SubjectId")
                                .HasColumnType("integer")
                                .HasColumnName("subject_id");

                            b1.HasKey("FeedbackId");

                            b1.ToTable("feedbacks", "ratings");

                            b1.WithOwner()
                                .HasForeignKey("FeedbackId");
                        });

                    b.Navigation("Receiver")
                        .IsRequired();
                });

            modelBuilder.Entity("RatingService.Domain.Entities.Participant", b =>
                {
                    b.HasOne("RatingService.Domain.Aggregates.EventInfo", null)
                        .WithMany("Participants")
                        .HasForeignKey("EventInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RatingService.Domain.Aggregates.UserInfo", null)
                        .WithMany("Participations")
                        .HasForeignKey("UserInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RatingService.Domain.Entities.ParticipantRatingUpdate", b =>
                {
                    b.HasOne("RatingService.Domain.Entities.Ratings.ParticipantRating", null)
                        .WithMany("Updates")
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RatingService.Domain.Entities.Ratings.EventRating", b =>
                {
                    b.HasOne("RatingService.Domain.Aggregates.EventInfo", null)
                        .WithOne("Rating")
                        .HasForeignKey("RatingService.Domain.Entities.Ratings.EventRating", "EventInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RatingService.Domain.Entities.Ratings.OrganizerRating", null)
                        .WithMany("EventRatings")
                        .HasForeignKey("OrganizerRatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RatingService.Domain.Entities.Ratings.GamerRating", b =>
                {
                    b.HasOne("RatingService.Domain.Aggregates.UserInfo", null)
                        .WithOne("GamerRating")
                        .HasForeignKey("RatingService.Domain.Entities.Ratings.GamerRating", "UserInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RatingService.Domain.Entities.Ratings.OrganizerRating", b =>
                {
                    b.HasOne("RatingService.Domain.Aggregates.UserInfo", null)
                        .WithOne("OrganizerRating")
                        .HasForeignKey("RatingService.Domain.Entities.Ratings.OrganizerRating", "UserInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RatingService.Domain.Entities.Ratings.ParticipantRating", b =>
                {
                    b.HasOne("RatingService.Domain.Entities.Ratings.GamerRating", null)
                        .WithMany("ParticipantRatings")
                        .HasForeignKey("GamerRatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RatingService.Domain.Entities.Participant", null)
                        .WithOne("Rating")
                        .HasForeignKey("RatingService.Domain.Entities.Ratings.ParticipantRating", "ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RatingService.Domain.Aggregates.EventInfo", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Participants");

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("RatingService.Domain.Aggregates.UserInfo", b =>
                {
                    b.Navigation("GamerFeedbacks");

                    b.Navigation("GamerRating");

                    b.Navigation("OrganizerFeedbacks");

                    b.Navigation("OrganizerRating");

                    b.Navigation("Participations");
                });

            modelBuilder.Entity("RatingService.Domain.Entities.Participant", b =>
                {
                    b.Navigation("Rating");
                });

            modelBuilder.Entity("RatingService.Domain.Entities.Ratings.EventRating", b =>
                {
                    b.Navigation("Updates");
                });

            modelBuilder.Entity("RatingService.Domain.Entities.Ratings.GamerRating", b =>
                {
                    b.Navigation("ParticipantRatings");
                });

            modelBuilder.Entity("RatingService.Domain.Entities.Ratings.OrganizerRating", b =>
                {
                    b.Navigation("EventRatings");
                });

            modelBuilder.Entity("RatingService.Domain.Entities.Ratings.ParticipantRating", b =>
                {
                    b.Navigation("Updates");
                });
#pragma warning restore 612, 618
        }
    }
}
