services:
  #Auth Db
  auth-db:
    image: "postgres:latest"
    container_name: auth-db
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=123w
  #tokens cache
  refresh-token-cache:
    image: "redis:latest"
    container_name: refresh-token-cache
    restart: always
    ports:
      - 6380:6379
  #Auth Api
  auth-api:
    build:
      context: Gb.AuthService
      # dockerfile: Gb.AuthService/Dockerfile
    container_name: auth-api
    ports:
      - 7070:8080
      - 7071:8081
    environment:
      - "PG_CONNECT=Host=auth-db;Database=usersdb;Username=postgres;Password=123w;"
      - REDIS_CONNECT=refresh-token-cache
    restart: always
    depends_on:
      - refresh-token-cache
      - auth-db

  #Events Db
  events-db:
    image: "postgres:latest"
    container_name: events-db
    restart: always
    ports:
      - 5434:5432
    environment:
      - POSTGRES_PASSWORD=123w
  #Web Api
  events-api:
    build:
      context: Gb.EventsService
      # dockerfile: Gb.EventsService/Dockerfile
    container_name: events-api
    environment:
      - "PG_CONNECT=Host=events-db;Database=eventsdb;Username=postgres;Password=123w;"
      - REDIS_CONNECT=refresh-token-cache
    restart: always
    ports:
      - 7072:8080
      - 7073:8081
    depends_on:
      - events-db
