# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test GamerProfileService

# триггер
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # ручной запуск
  workflow_dispatch:

jobs:
  build-and-test:
    # среда
    runs-on: ubuntu-latest
    
    # переменные окружения
    env:
      PROJECT_PATH: src/Gb.GamerProfileService/Gb.Gps.WebHost/Gb.Gps.WebHost.csproj
      PROJECT_PATH_TESTS: src/Gb.GamerProfileService/Gb.Gps.UnitTests/Gb.Gps.UnitTests.csproj

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}
      
    - name: Build project
      run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore
      
    - name: Run tests
      run: dotnet test ${{ env.PROJECT_PATH_TESTS }} # --verbosity normal
