# https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images

name: Create new image of GamerProfileService

# триггер
on:
  push:
    branches: [ "imagePush" ]
  # ручной запуск
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    # среда
    runs-on: ubuntu-latest

    # Sets the permissions granted to the GITHUB_TOKEN for the actions in this job.
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the GitHub Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v2
      with:
        context: GameBy/src/GamerProfileService
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: GameBy/src/GamerProfileService/GamerProfileService/Dockerfile

#    - name: Generate artifact attestation
#      uses: actions/attest-build-provenance@v1
#      with:
#        subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
#        subject-digest: ${{ steps.push.outputs.digest }}
#        push-to-registry: true
